import { Poppins } from "next/font/google";
import "./globals.scss";

import CustomCursor from "@/ui/cursor/custom-cursor";
import Header from "@/ui/header/header";

const geistSans = Poppins({
    variable: "--font-geist-sans",
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
    title: "Yash Pathik | Portfolio",
    description: "Web developer portfolio generated by nextjs and scss.",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={geistSans.variable}>
                <CustomCursor />
                <Header />
                {children}
            </body>
        </html>
    );
}
